services:
    _defaults:
        public: true
        tags:
            - { name: 'prooph_service_bus.gogart_command_bus.route_target', message_detection: true }

    command_handler.product.add:
        class: Gogart\Application\Product\Command\Handler\AddProductHandler
        arguments:
            - '@repository.product'

    command_handler.product.change_title:
        class: Gogart\Application\Product\Command\Handler\ChangeProductTitleHandler
        arguments:
            - '@repository.product'

    command_handler.product.change_price:
        class: Gogart\Application\Product\Command\Handler\ChangeProductPriceHandler
        arguments:
            - '@repository.product'

    command_handler.product.remove:
        class: Gogart\Application\Product\Command\Handler\RemoveProductHandler
        arguments:
            - '@repository.product'

    command_handler.cart.add:
        class: Gogart\Application\Cart\Command\Handler\AddCartHandler
        arguments:
            - '@repository.cart'

    command_handler.cart.add_product_to_cart:
        class: Gogart\Application\Cart\Command\Handler\AddProductToCartHandler
        arguments:
            - '@repository.cart'
            - '@repository.product'