services:
    _defaults:
        public: true

    query_handler.product.list:
        class: Gogart\Application\Product\Query\Handler\ListProductHandler
        arguments:
            - '@read_repository.product'

    query_handler.cart:
        class: Gogart\Application\Cart\Query\Handler\CartHandler
        arguments:
            - '@read_repository.cart'
