services:
    repository.product:
        class: Gogart\Infrastructure\Model\Product\Repository\ProductRepository
        factory: ["@doctrine", "getRepository"]
        arguments:
            - Gogart\Model\Product\Product

    read_repository.product:
        class: Gogart\Infrastructure\Application\Product\Query\Repository\ProductReadRepository
        arguments:
            - '@doctrine.dbal.default_connection'
