prooph_event_store:
    stores:
        cart_store:
            event_store: Prooph\EventStore\Pdo\MySqlEventStore
            repositories:
                repository.cart:
                    repository_class: Gogart\Infrastructure\Model\Cart\Repository\CartRepository
                    aggregate_type: Gogart\Model\Cart\Cart
                    aggregate_translator: prooph_event_sourcing.aggregate_translator
    projection_managers:
        cart_projection_manager:
            event_store: Prooph\EventStore\Pdo\MySqlEventStore
            connection: 'doctrine.pdo.connection'
            projections:
                cart_projection:
                    read_model: 'read_model.cart'
                    projection: Gogart\Infrastructure\Projection\CartProjection

services:
    Prooph\EventStore\Pdo\MySqlEventStore:
        arguments: ['@prooph_event_store.message_factory', '@doctrine.pdo.connection', '@prooph_event_store.single_stream_strategy']

    doctrine.pdo.connection:
        class: PDO
        factory: ['@database_connection', getWrappedConnection]

    prooph_event_store.single_stream_strategy:
        class: Prooph\EventStore\Pdo\PersistenceStrategy\MySqlSingleStreamStrategy

    prooph_event_sourcing.aggregate_translator:
        class: Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator