product_add:
    path: /products
    methods: [POST]
    defaults: { _controller: 'controller.product:add' }

product_change_title:
    path: /products/{productId}/title
    methods: [PATCH]
    defaults: { _controller: 'controller.product:changeTitle' }

product_change_price:
    path: /products/{productId}/price
    methods: [PATCH]
    defaults: { _controller: 'controller.product:changePrice' }

product_remove:
    path: /products/{productId}
    methods: [DELETE]
    defaults: { _controller: 'controller.product:remove' }

product_list:
    path: /products
    methods: [GET]
    defaults: { _controller: 'controller.product:list' }

cart_add:
    path: /carts
    methods: [POST]
    defaults: { _controller: 'controller.cart:addCart' }

cart_add_product_to_cart:
    path: /carts/{cartId}/products/{productId}
    methods: [POST]
    defaults: { _controller: 'controller.cart:addProduct' }

cart_remove_product_from_cart:
    path: /carts/{cartId}/products/{productId}
    methods: [DELETE]
    defaults: { _controller: 'controller.cart:removeProduct' }

cart_get:
    path: /carts/{cartId}
    methods: [GET]
    defaults: { _controller: 'controller.cart:get' }
