product_add:
    path: /products
    methods: [POST]
    defaults: { _controller: 'controller.product:add' }

product_change_title:
    path: /products/{productId}/title
    methods: [PATCH]
    defaults: { _controller: 'controller.product:changeTitle' }

product_change_price:
    path: /products/{productId}/price
    methods: [PATCH]
    defaults: { _controller: 'controller.product:changePrice' }